#!/bin/bash
echo "======================================================================"
echo "Demo: Chat with MCP Tools"
echo "======================================================================"
echo ""
echo "Make sure you set: export OPENAI_API_KEY='sk-...'"
echo ""
echo "Then run:"
echo "   uv run python chat_with_mcp.py"
echo ""
echo "Try these questions:"
echo "  • 'What namespaces exist?'"
echo "  • 'Show me all pods in kube-system'"
echo "  • 'Are there any issues in default namespace?'"
echo "  • 'What nodes do I have and what pods are on them?'"
echo ""
